In [29]:
df.describe()

,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input
count,4096.000000,4096.000000,4096.000000,4096.000000,4096.000000,4096.000000,4096.000000
mean,181.443726,5.920327,80.827004,19.467529,0.049675,0.038477,0.029541
std,70.644633,3.460342,12.929865,57.332804,0.022216,0.344373,0.310549
min,40.000000,4.025000,53.462278,0.000000,0.000000,0.000000,0.000000
25%,131.000000,4.025000,69.755759,0.000000,0.037500,0.000000,0.000000
50%,165.666667,4.186000,81.007930,0.000000,0.041667,0.000000,0.000000
75%,222.000000,6.440000,89.834402,8.000000,0.070833,0.000000,0.000000
max,444.000000,37.513000,167.322581,621.000000,0.091667,5.200000,4.000000

In [30]:
df.isna().sum()

time                      0
glucose                   0
calories                  0
heart_rate                0
steps                     0
basal_rate                0
bolus_volume_delivered    0
carb_input                0
dtype: int64

In [31]:
df.columns

Index(['time', 'glucose', 'calories', 'heart_rate', 'steps', 'basal_rate',
       'bolus_volume_delivered', 'carb_input'],
      dtype='str')

In [32]:
df.dtypes

time                          str
glucose                   float64
calories                  float64
heart_rate                float64
steps                     float64
basal_rate                float64
bolus_volume_delivered    float64
carb_input                float64
dtype: object

In [33]:
df.shape

(4096, 8)

In [34]:
import os
print(os.getcwd())

print(os.listdir("."))
print(os.listdir(".."))

c:\Users\Lenovo\Documents\GitHub\diabetes-cgm-analysis
['.git', '.gitattributes', '.gitignore', '01_explore.ipynb', 'data', 'notebooks', 'README.md', 'sql', 'src']
['desktop-tutorial', 'diabetes-cgm-analysis']

In [35]:
import pandas as pd

df = pd.read_csv("data/raw/HUPA0001P.csv", sep = ";")

df.head()

,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input
0,2018-06-13T18:40:00,332.0,6.3595,82.322835,34.0,0.091667,0.0,0.0
1,2018-06-13T18:45:00,326.0,7.7280,83.740157,0.0,0.091667,0.0,0.0
2,2018-06-13T18:50:00,330.0,4.7495,80.525180,0.0,0.091667,0.0,0.0
3,2018-06-13T18:55:00,324.0,6.3595,89.129032,20.0,0.091667,0.0,0.0
4,2018-06-13T19:00:00,306.0,5.1520,92.495652,0.0,0.075000,0.0,0.0